spring:
  application:
    name: spring-boot-essentials-jpa
  datasource:
    url: jdbc:sqlite:./gym.sqlite
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true